--- #YAML:1.0
name:               Data-Show
version:            0.002002
abstract:           Dump data structures with name and point-of-origin
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:  1.17
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
